test_youtube_search_responses = [
    {'kind': 'youtube#searchResult', 'etag': 'AX0x1FgMw18qzNHxS4N_vYPBO6s', 'id': {'kind': 'youtube#video', 'videoId': 'pHMbt3-k_oM'}, 'snippet': {'publishedAt': '2023-01-26T12:07:31Z', 'channelId': 'UC0zjODUrI0kcZT_2XwmWVGA', 'title': 'POV: Noobs first shopping spree- 😱🤩🤑', 'description': "ʚ— heyyy I'm Amber ✌️ ꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷꒦꒷ ╭ 。‧ ☆ ┊ Follow my ...", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/pHMbt3-k_oM/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/pHMbt3-k_oM/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/pHMbt3-k_oM/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'NotAmberRoblox', 'liveBroadcastContent': 'none', 'publishTime': '2023-01-26T12:07:31Z'}},
    {'kind': 'youtube#searchResult', 'etag': '4CAL38rI853JneclnAOjqzvwQ-8', 'id': {'kind': 'youtube#video', 'videoId': 'z96a06xfknA'}, 'snippet': {'publishedAt': '2023-06-17T04:51:16Z', 'channelId': 'UCddKNh1k9L22Hd5ALO-F3qg', 'title': 'Roblox shopping spree! ||~800~||', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/z96a06xfknA/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/z96a06xfknA/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/z96a06xfknA/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'mwnni', 'liveBroadcastContent': 'none', 'publishTime': '2023-06-17T04:51:16Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'fqgaO9GwiSPkR4rrZuRc-9A50Eo', 'id': {'kind': 'youtube#video', 'videoId': 'i_uHZCZOQ2g'}, 'snippet': {'publishedAt': '2023-07-25T02:04:47Z', 'channelId': 'UCIhMr5iSPlBkXvG6_E3Gy5w', 'title': '1.6k Shopping spree! First time getting robux!', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/i_uHZCZOQ2g/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/i_uHZCZOQ2g/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/i_uHZCZOQ2g/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Frxch Aloha', 'liveBroadcastContent': 'none', 'publishTime': '2023-07-25T02:04:47Z'}},
    {'kind': 'youtube#searchResult', 'etag': '01gNWMZucA2aifc4GSZuXKxEE00', 'id': {'kind': 'youtube#video', 'videoId': 'dFv2w6sKCac'}, 'snippet': {'publishedAt': '2023-03-27T18:13:25Z', 'channelId': 'UCe7AfmXoBmqbNYveB1tmZkg', 'title': '100 robux shopping spree! First time getting robux!', 'description': 'Hey Hey! Enjoy the video! Music credits: Music: Denim Musician: EnjoyMusic URL: https://enjoymusic.ai Music: Flow Musician: ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/dFv2w6sKCac/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/dFv2w6sKCac/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/dFv2w6sKCac/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'iiAvaxPlays', 'liveBroadcastContent': 'none', 'publishTime': '2023-03-27T18:13:25Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'qhBaBCKa-1Gu54bNalg9XSorPaY', 'id': {'kind': 'youtube#video', 'videoId': 'UzM-0DMYJ0w'}, 'snippet': {'publishedAt': '2023-03-08T15:00:45Z', 'channelId': 'UCl5yFCBpNHQkVW7YO6vaFxQ', 'title': 'GETTING ROBUX FOR THE FIRST TIME! + SHOPPING SPREE! 😱⚡️ *BOUGHT VIP IN ADOPT ME* || Roblox', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/UzM-0DMYJ0w/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/UzM-0DMYJ0w/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/UzM-0DMYJ0w/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'hayley roblox', 'liveBroadcastContent': 'none', 'publishTime': '2023-03-08T15:00:45Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'Xesy4vpIWaChNvLycKSpkWJcVYs', 'id': {'kind': 'youtube#video', 'videoId': '12_7mUB92nI'}, 'snippet': {'publishedAt': '2022-04-30T00:55:58Z', 'channelId': 'UCpP5Cu4XU8HJcNO0UfBPV9Q', 'title': '800 robux shopping spree 🛍🛍 (FIRST TIME GETTING ROBUX)', 'description': "Hey guys it's lyxy! ^_^ This is my first time getting robux:) Follow me on roblox! User: Pinklyxy ;D And subscribe 4 free ice cream ...", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/12_7mUB92nI/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/12_7mUB92nI/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/12_7mUB92nI/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'lyxyflowers', 'liveBroadcastContent': 'none', 'publishTime': '2022-04-30T00:55:58Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'qcdpbpV4N4wyRUeAUrEML00YMOk', 'id': {'kind': 'youtube#video', 'videoId': 'X-W_5M6d5EQ'}, 'snippet': {'publishedAt': '2023-07-17T20:00:07Z', 'channelId': 'UCInSzlia-kS-XTHPaAoBObA', 'title': 'Apple shopping spree!! $$$ #airpods #iphone', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/X-W_5M6d5EQ/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/X-W_5M6d5EQ/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/X-W_5M6d5EQ/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Brianna Renee', 'liveBroadcastContent': 'none', 'publishTime': '2023-07-17T20:00:07Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'xD5SVI5XEbMt3hHrRxqQa_i4HXA', 'id': {'kind': 'youtube#video', 'videoId': '-qcY9ptUC3c'}, 'snippet': {'publishedAt': '2022-08-01T08:07:40Z', 'channelId': 'UCe_f5uRUKjdae-0HwblmcWw', 'title': 'Shopping Spree / First Time Getting Robux TikTok Compilation', 'description': 'tags: first time getting robux, Getting Robux for the first Time, buying robux for the first time, Roblox shopping spree, free robux, ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/-qcY9ptUC3c/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/-qcY9ptUC3c/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/-qcY9ptUC3c/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'CudieCat 【キューディーキャット】', 'liveBroadcastContent': 'none', 'publishTime': '2022-08-01T08:07:40Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'p2QMaxMd9vSeE5OY0LGKYldAWCU', 'id': {'kind': 'youtube#video', 'videoId': 'IYwGIguxXGc'}, 'snippet': {'publishedAt': '2024-01-17T23:59:30Z', 'channelId': 'UCQO7Yfd8YRAOFNJ3TzhRkpw', 'title': '801 shopping spree sorry if there was no music  *not trying to brag*preppy #youtubeshorts', 'description': '', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/IYwGIguxXGc/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/IYwGIguxXGc/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/IYwGIguxXGc/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Simplyxlayla', 'liveBroadcastContent': 'none', 'publishTime': '2024-01-17T23:59:30Z'}},
    {'kind': 'youtube#searchResult', 'etag': 'X4tt7AadiXgXCVyrsixCQunLK3Y', 'id': {'kind': 'youtube#video', 'videoId': 'YdTaNwqP72c'}, 'snippet': {'publishedAt': '2021-10-16T15:22:40Z', 'channelId': 'UCMpV7_F45LF73U9H_W0x5Sw', 'title': 'Getting robux for the first time! 160 robux shopping spree!', 'description': 'Hey guys!! I just got robux!! Yay! 160 robux!! This is my first video on YouTube so the editing is not so good. I hope you enjoy!', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/YdTaNwqP72c/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/YdTaNwqP72c/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/YdTaNwqP72c/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Avani Agrawal', 'liveBroadcastContent': 'none', 'publishTime': '2021-10-16T15:22:40Z'}},
]

test_youtube_urls = [
    "https://www.youtube.com/watch?v=FhYCGRoWN9M",
    "https://www.youtube.com/watch?v=7S9q1kAVmc0",
    "https://www.youtube.com/watch?v=3cugR5eQA5s",
    "https://www.youtube.com/watch?v=9-QVDvOpijc",
    "https://www.youtube.com/watch?v=oWlUHjs8q2A",
    "https://www.youtube.com/watch?v=Ipe9xJCfuTM",
    "https://www.youtube.com/watch?v=a3fnMbl-BFw",
    "https://www.youtube.com/watch?v=YEyKh1ZtsQU",
    "https://www.youtube.com/watch?v=LwD7mv8Mb7o",
    "https://www.youtube.com/watch?v=3DyMdbSh9tQ",
]
